apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky-app
  template:
    metadata:
      labels:
        app: tasky-app
    spec:
      containers:
      - name: tasky-app
        image: us-central1-docker.pkg.dev/clgcporg10-166/tasky-docker-images/tasky-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: tasky-app-config
              key: MONGODB_URI
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tasky-secret
              key: secret-key


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: tasky-app-config
  namespace: default 
data:
  MONGODB_URI: "mongodb://10.10.1.2:27017/"


---

apiVersion: v1
kind: Secret
metadata:
  name: tasky-secret
data:
  secret-key: dmFsdWUtMg0KDQo=